### ISSUE TITLE
Registry batch reb files need a cleanup

### ISSUE THREAD

**Issue by Karneades** [EricZimmerman/RECmd#11]
This issue is not a feature request per se but a placeholder for a needed cleanup for the *ASEP batch examples. We have duplicates, similar keys in different files, different naming or categories for the same key... Also RegistryASEPs.reb includes all the others but not fully and we have differences between the files, e.g. some entries are only there and some only in the more specific files.

I don't think that rep includes are possible inside other .reb files (like compounds in Kape) but if we duplicate entries from the more specific into one generic "RegistryASEPs.reb" error occur or additions only made in one file.

We could of course remove RegistryASEPs.reb entirely to only have the specific files.

**Question:** What do you think? Do other work with those and see a value of fixing the differences?

https://github.com/EricZimmerman/RECmd/blob/master/BatchExamples/
* RegistryASEPs.reb
* SoftwareASEPs.reb
* SystemASEPs.reb
* ...

I think it is of value to cleanup them: remove duplicates, fix the differences, align the category names and keys to make the analysis easier. Furthermore, I would fix https://github.com/EricZimmerman/KapeFiles/blob/master/Modules/Registry/RECmd.mkape  so either RegistryASEPs.reb is used or all the others, but not both (because of duplicated information).

_If this place is wrong for such an issue, then please advice._

**Comment by rathbuna** [comment]
I have been working on a solution to this problem that will be forthcoming in the very near future. It'll be a new Batch file with a corresponding Module for that particular Batch file. It'll solve a lot of issues with the duplication of entries, entries that aren't providing any meaningful data output, and consolidating the most useful entries with meaningful comments to help examiners understand what they're looking at. Stay tuned.

**Comment by rathbuna** [comment]
Once I realized there were other Batch files that were going unused, and frankly, most people including myself didn't know existed until I looked, I added them to the module as a temporary solution awaiting a more permanent solution, which I got to work on almost immediately after that discovery. It's almost done for initial release and hopefully will go live within the next week once I do final cleanup to it.

**Comment by rathbuna** [comment]
@Karneades https://www.github.com/EricZimmerman/RECmd/tree/master/BatchExamples%2FKroll_Batch.reb was added last night. Let me know your thoughts. 1.0 for now but it'll be continually added to until I'm satisfied 😋

**Comment by Karneades** [comment]
yeah, looks cool, it's now more of a targeted extraction (more like a RegRipper profile) than a generic extraction like some of the other batch files. it provides relevant things from different places. and from different hives, which is cool.
