### ISSUE TITLE
SAM information seems incorrect

### ISSUE THREAD

**Issue by sjosz** [EricZimmerman/RECmd#4]
Hi,

I'm currently doing an IR investigation and I'm planning on doing a check on all SAM registry files to see if all local admin passwords have been resetted, The REcmd tool is perfect for that, except that it seems to always show 'False' where the value is a boolean. 

The version of REcmd that I'm using is '1.5.2.0' combine the command:
ReCmd.exe --f "D:\Registry\SAM_dc" --bn RECmd_Batch_MC.reb --csv D:\output

![Raew5KB9wR](https://user-images.githubusercontent.com/11965973/75096585-0fca7200-55c7-11ea-8fe9-ef0a173e799f.png)

I've also attached a SAM registry file for convenience.  
[SAM.zip](https://github.com/EricZimmerman/RECmd/files/4239684/SAM.zip)

Is this a bug?

I appreciate all your hard work on these tools, they have been very beneficial so far, thank you!

**Comment by EricZimmerman** [comment]
It's just decoding the data that is present in the sam values. I can take a
look but usually you need something like Sam Inside to get all the details

Have you looked at the plugin source code to see what is sitting at the
offset where that value is coming from?

**Comment by sjosz** [comment]
Thanks for your quick response. I will try to take a look at the plugin source code, but I'm not a coder so it will take some time probably.

**Comment by EricZimmerman** [comment]
https://github.com/EricZimmerman/RegistryPlugins/blob/master/RegistryPlugin.SAM/UserAccounts.cs#L177

https://github.com/EricZimmerman/RegistryPlugins/blob/master/RegistryPlugin.SAM/UserOut.cs#L57

the first link shows where the flags are. could it be there isnt enough data for the flags to exist at all, hence they are all False?

**Comment by sjosz** [comment]
Thank you! I will check it out this weekend when I'm less busy dealing with his investigation.

**Comment by sjosz** [comment]
I changed the source code slightly, it now points to the correct value: https://github.com/EricZimmerman/RegistryPlugins/compare/master...sjosz:patch-1

**Comment by EricZimmerman** [comment]
nice. can you do a PR?

**Comment by sjosz** [comment]
Done.

**Comment by EricZimmerman** [comment]
this is committed and will be in next release! thanks for the report and fix
