### ISSUE TITLE
Batch file: How to find values with specific data

### ISSUE THREAD

**Issue by Karneades** [EricZimmerman/RECmd#42]
Malware uses new file associations with the exefile handler to bypass AVs. E.g. adding a registry key for `.test` under `Classes` and for the default value use `exefile`. I would like to add an entry to the Kroll batch file to find all file associations which use the exefile file handler (normally only one, the .exe one).

How should the entry look like in a batch file to iterate through all values for a given key and find those with specific data?

I added a Sigma rule for that https://github.com/Karneades/sigma/blob/master/rules/windows/registry_event/win_registry_file_association_exefile.yml or our team tweeted about that too https://twitter.com/swisscom_csirt/status/1463070008867704835

**Comment by EricZimmerman** [comment]
You'd want to use the search options to find these vs batch file

**Comment by Karneades** [comment]
Yes. Looked through all the batch files, not found any example for the search options.

**Comment by AndrewRathbun** [comment]
@Karneades in RECmd:

```
        sa              Search for <string> in keys, values, data, and slack.
        sk              Search for <string> in key names.
        sv              Search for <string> in value names
        sd              Search for <string> in value record's value data
        ss              Search for <string> in value record's value slack
```

**Comment by EricZimmerman** [comment]
If the malware uses a clear pattern, you can use some of the wild card features to be able to try and find what it is you're looking for in a batch file too

**Comment by Karneades** [comment]
@AndrewRathbun  thanks, I'm aware of those. But how to reflect e.g. sd in a Batch file? I would like to search for `exefile` in each value data for all subkeys under classes. But it was just a AV bypass lately and I thought to add that search. It's not that important though in overall view :)

**Comment by AndrewRathbun** [comment]
I figured that's what you were getting at, was just clarifying for the record what Eric mentioned here: https://github.com/EricZimmerman/RECmd/issues/42#issuecomment-991077647

If there's a way to regex and use search and all that within Batch files, that's news to me. Once we figure our proper syntax for that, @Karneades there's definitely room to enhance the Kroll Batch File.

**Comment by Karneades** [comment]
OK, so i could make a KAPE file which triggers that search using REcmd's features but at the moment not directly with REcmd batch files. Thanks for clarification.

**Comment by AndrewRathbun** [comment]
> 

Yes but just because I'm not aware of being able to use `Refine: ` like in EvtxECmd Maps doesn't mean it's not a feature that's currently implemented. I think only @EricZimmerman can advise whether there's some logic for that, short of searching the repo for `Refine` or something like that to see if there's something similar to how EvtxECmd does it.

**Comment by EricZimmerman** [comment]
No. Batch mode is not for hunting like that. The sk and related switches do that. 

Since batch mode supports wildcard characters, though, that's where I'm saying you could potentially do some brute force style things, but the only way to see if it works is to try it

**Comment by AndrewRathbun** [comment]
There's some hits on `Refine` [here](https://github.com/EricZimmerman/evtx/blob/9cba6e014c3a6ae42f481d2411da670cb8544899/evtx/EventLogMap.cs#L57) and [here](https://github.com/EricZimmerman/evtx/blob/f4e8ecae4da2bcb42e078772f39d9db05d94fff4/evtx/EventRecord.cs#L323) but not seeing anything like that in the RECmd repo.

**Comment by Karneades** [comment]
> Since batch mode supports wildcard characters, though, that's where I'm saying you could potentially do some brute force style things, but the only way to see if it works is to try it

I'm not sure what you mean. I'm unable to search for the value data. Only key search is possible.

**Comment by Karneades** [comment]
FTR for future readers. Idea is now creating a KAPE module to get those values into a file instead of adding these keys to existing batch files.
```
RECmd.exe --f <path to user profile folder>\AppData\Local\Microsoft\Windows\UsrClass.dat --sd "exefile"
RECmd.exe --f <path to root dir>\C\Windows\System32\config\SOFTWARE --vn classes --sd "exefile"
```

**Comment by AndrewRathbun** [comment]
@Karneades maybe we could make a Threat Hunting Module that could string together some of these commands and output to a file(s) that are appropriately named. What are your thoughts?

**Comment by Karneades** [comment]
Using the most current RECmd version with --csv doesn't create an output file. I don't know why, maybe I miss the correct usage ;)

I think such a threat hunting module using a specific registry search would help.. I'm note sure how many of such searches will be there.. I would omit having yet another repository of malware IOCs. But generic search in addition to the other files would be cool. E.g. powershell, wscript, javascript, .. in value data.

I played around now and made a compound which includes different RECmd modules, e.g. for exefile search and output is a textfile (because of the issue outlined in the first sentence).
