### ISSUE TITLE
Unable to load live registry in RegExplorer 1.6

### ISSUE THREAD

**Issue by CollinChaffin** [EricZimmerman/RECmd#43]
** RECmd version # **
1.6 RegExplorer

**Describe the bug**
```
Attempt to get an MFT record with an old reference, Error message: Attempt to get an MFT record with an old reference, Stack trace:    at DiscUtils.Ntfs.MasterFileTable.GetRecord(FileRecordReference fileReference)
   at DiscUtils.Ntfs.File.LoadAttributes()
   at DiscUtils.Ntfs.NtfsFileSystem..ctor(Stream stream)
   at RawCopy.Helper.VerifyFileSystemOpen(String path) in D:\Code\RawCopy\RawCopy\Helper.cs:line 457
   at RawCopy.Helper.RawFileExists(String path) in D:\Code\RawCopy\RawCopy\Helper.cs:line 141
   at RawCopy.Helper.GetFiles(List`1 fileNames, Boolean dedupe) in D:\Code\RawCopy\RawCopy\Helper.cs:line 65
   at RegistryExplorer.Forms.Main.<LoadHive>d__45.MoveNext() in D:\Code\RegistryViewerZ\RegistryViewerZ\Forms\Main.cs:line 885
```

**To Reproduce**
1. Go to File, Live System, attempt to open SOFTWARE,SYSTEM, or current user hive
2. No hive opens, messages shows error above

**Expected behavior**
Open live hives

**Comment by EricZimmerman** [comment]
This is just one of those things that sometimes happens and there really isn't a workaround except to try again or possibly reboot the computer

I wish there was something else I could do to make  it worked but to date I haven't found any way to do it short of what I mentioned above

**Comment by CollinChaffin** [comment]
Ok thanks I have rebooted, run chkdsk, etc. I know I had used it before on this system and loved it, just can't explain why it suddenly can't open the live hives.  If I open a live hive of a non-logged in user, it does work but I really need to load the machine hives.

**Comment by EricZimmerman** [comment]
You could also try using kape to pull the registry hives off the running
system but you may end up running into the same problem.

**Comment by CollinChaffin** [comment]
If it helps, just to verify there wasn't an issue with the registry itself, in addition to standard regedit, I ran regcool (another similar 3rd party utility for offline/live hives) and it did open the live hives without issue.

**Comment by EricZimmerman** [comment]
Yeah, there are certainly other techniques to allow to be opened, including creating a volume shadow copy and reading it from there etc. But I'm doing a raw disk read which is leading to the discrepancy for whatever reason

In the past when I've seen that error occur, it generally resolves itself with some time passing and or reboot, but I haven't been able to figure out exactly what triggers it

**Comment by CollinChaffin** [comment]
Yea not sure what technique regcool uses but doubt it's shadow copy as quickly as it opens (almost as fast as regedit).  Like I said I remember using regexplorer in the past (been a while) and creating bookmarks and using the library of them which is absolutely invaluable.  I love your tools, this is literally the first time I've ever run into any issue with them!

**Comment by CollinChaffin** [comment]
Just to rule out anything else, I ran a registry compress/compact to ensure there wasn't something corrupted - same results I'm pulling my hair out.  I do appreciate you replying so quickly!  Is there anything else you can think of for me to try?  Between everything else I've tried (offline chkdsk/reg compress), I'm up to 9 reboots now.
