### ISSUE TITLE
RLA --out parameter 

### ISSUE THREAD

**Issue by nrrpinto** [EricZimmerman/RECmd#47]
** RECmd version # **
2.0.0.0

**Describe the bug**
RLA command line, does not correctly build the output directory.
Executed Command line:  C:\tools\rla\rla.exe -f "C:\test_pinqp\DESKTOP-B3FG6UV\C\Windows\System32\config\SOFTWARE" --out "C:\test_pinqp\DESKTOP-B3FG6UV\C\Windows\System32\config\SOFTWARE\output"

**To Reproduce**
1. Create output folder: mkdir "C:\test_pinqp\DESKTOP-B3FG6UV\C\Windows\System32\config\SOFTWARE\output"
2. Execute RLA with file source and out parameter. Please see above.

**Expected behavior**
Expected to clean the dirty HIVE to the new folder defined in the --out parameter.

**Screenshots**
![image](https://user-images.githubusercontent.com/29933547/178350217-66c5e4c6-4606-437a-b751-5f9ec62c5e7a.png)

**Additional context**
Issue might be at line 535 and 536 of the source code:
    var outFile = hiveToProcess.Replace(":", "").Replace(Path.PathSeparator.ToString(), "_");
    var outFileAll = Path.Combine(@out, outFile);

**Comment by EricZimmerman** [comment]
this is fixed. upload will happen in a few

**Comment by EricZimmerman** [comment]
its up

**Comment by AndrewRathbun** [comment]
Great stuff, thanks Eric
