### ISSUE TITLE
get all information from hive

### ISSUE THREAD

**Issue by ohanaali** [EricZimmerman/RECmd#5]
Is there a way extracting all information to a csv from a hive (including deleted keys and values.

i have tried 
recmd.exe --f "myhive" --nl --csv "mycsv.csv" --recover --details --regex --sa *
recmd.exe --f "myhive" --nl --csv "mycsv.csv" --recover --details --regex --sa .*

but no result found

**Comment by EricZimmerman** [comment]
it does not work that way

you want batch mode, not one of the search options.

create a new batch file and go that route, tho pulling in all info seems overkill
