### ISSUE TITLE
RLA --out parameter

### ISSUE THREAD

**Issue by dfirenti8** [EricZimmerman/RECmd#55]
** RECmd version # 
2.0.0.0

**Describe the bug**
RLA command line, does not correctly export to the output directory.
Command line: -d C:\temp\registry --out C:\temp\registry\output

**To Reproduce**
Create Output folder
Execute RLA with file source and out parameter. Please see above.

**Expected behavior**
Expected to clean the dirty HIVE to the new folder defined in the --out parameter.

This was previously identified and resolved in RLA --out parameter #47
https://github.com/EricZimmerman/RECmd/issues/47

**Screenshots**
![Screenshot 2024-01-25 160344](https://github.com/EricZimmerman/RECmd/assets/157674418/92d69194-a12b-4827-89d8-ccf8033f56cd)

**Comment by EricZimmerman** [comment]
This looks correct. It's preserving the source path.

**Comment by dfirenti8** [comment]
Shouldn't the outputted files be dumped to the C:\temp\registry\output\ directory. It appears that it dumps the files in C:\temp\registry\output\C\temp\registry (it seems to create additional directories C\temp\registry in the output directory)
![Screenshot 2024-01-26 015902](https://github.com/EricZimmerman/RECmd/assets/157674418/4e6d79d7-399f-43d7-be2e-84510eaed129)

**Comment by EricZimmerman** [comment]
What if you had usrclass.dat registry hives from 20 different users? Wouldn't you want them all in the appropriate directories on a per user basis?

**Comment by dfirenti8** [comment]
ah good point. noted

**Comment by EricZimmerman** [comment]
This good to close then?

**Comment by dfirenti8** [comment]
Thanks
