### ISSUE TITLE
RLA --out parameter behaviour with -f 

### ISSUE THREAD

**Issue by Bloggzy** [EricZimmerman/RECmd#57]
**RLA version #**
2.0.0.0

**Describe the bug**
Note: As ever, an excellent tool and very grateful for all your efforts in creating and maintaining them!
RLA: when targeting a particular hive file with the -f parameter, the --out recreates the full directory path (not required in my use case).
Command line: 
`C:\DFIR\Tools\net6\rla.exe -f "E:\Testing\Hostname\Collection\Windows\System32\config\SAM" --out "E:\Testing\Hostname\Collection\Windows\System32\config\Clean"`

I've read the other issue entries and saw your comments in issue #55 about preserving the source path, in case you were processing multiple NTUSER.dat files (as an example), and I concur with this logic for the `-d` switch. But, I think for the `-f` switch where you are specifying a particular file it doesn't work as well? 

In my use case I am processing individual hives before running other tools on them seperately, so it is counter-productive for it to reproduce the full source path, for example the cleaned hive file gets output to the following directory:

`E:\Testing\Hostname\Collection\Windows\System32\config\Clean\E\Testing\Hostname\Collection\Windows\System32\config`

Note: If you can specify the paths using relative paths it seems to work (i.e. doesn't create the original source path), but I can't relative paths in my use case and have to use the full paths to each file / directory. e.g. I have my tools on C:\ and my artifacts on E:\.

**To Reproduce**
1. Copy a sample registry file to a directory
2. Run `C:\DFIR\Tools\net6\rla.exe -f "E:\Testing\Hostname\Collection\Windows\System32\config\SAM" --out "E:\Testing\Hostname\Collection\Windows\System32\config\Clean"`
3. Go to: `E:\Testing\Hostname\Collection\Windows\System32\config\Clean`
4. Find the preserved source path directory structure and follow it down to the clean file: `E:\Testing\Hostname\Collection\Windows\System32\config\Clean\E\Testing\Hostname\Collection\Windows\System32\config`

**Expected behavior**
When using the -f switch I would expect the clean file to be output to the path specified without retaining the source path. Or have another switch that enables / disables the preservation of the original source path?

**Screenshots**
![image](https://github.com/EricZimmerman/RECmd/assets/46377651/207886c0-1948-4d66-bd94-0d4a20ae49f6)

**Comment by Bloggzy** [comment]
I tried adding the tools directory to the PATH as suggested, but got similar results, in that, running it with the full paths specified resulted in the source path being included, and when using the relative path, the source path was not included.

I could certainly look at using this as a workaround to get the script working, but I do like your idea about adding a `--nop` switch as well!
![image](https://github.com/EricZimmerman/RECmd/assets/46377651/4c4ec90e-1a49-4661-9f99-64ac6041d772)

**Comment by Bloggzy** [comment]
I fully appreciate this is not urgent, but just inquiring how its going?

**Comment by EricZimmerman** [comment]
I'll try to get to it this week

**Comment by EricZimmerman** [comment]
this should be working.

--nop will end up like in test

without it test2

![image](https://github.com/EricZimmerman/RECmd/assets/4265254/c4384c6d-ad01-4bac-9683-4988bf89345e)

does this work? if so i can get a build to you

**Comment by Bloggzy** [comment]
That looks perfect, yes I would be happy to test it as and when you have a version built.

**Comment by EricZimmerman** [comment]
ok check for updates or redownload. we can reopen if theres issues

**Comment by Bloggzy** [comment]
Legend, thanks, I’ll test it tomorrow.
