### ISSUE TITLE
Ransomware warning

### ISSUE THREAD

**Issue by sbagmeijer** [EricZimmerman/RECmd#8]
Hi I tried to use the program to investigate some registry files, but windows seems to automatically quarantine the file and warn for: "Ransom:Win32/WannaCrypt.A!rfn".

The file that it warns on is: "RegistryExplorer.exe"

Just want to let you know.

![image](https://user-images.githubusercontent.com/1921261/82431233-b3c09e00-9a8e-11ea-9573-6379f0c624e3.png)

**Comment by EricZimmerman** [comment]
Nothing I can do about that.  It's a false positive so I would just restore it and allow it (assuming you got the file from my site)

You could upload it to virus total as well if you wanted a second opinion

**Comment by EricZimmerman** [comment]
as info, on latest windows 10 in slow ring, RE fired up without issue (1.5.2.0). no warnings, nothing

**Comment by sbagmeijer** [comment]
https://ericzimmerman.github.io/#!index.md

> All software is digitally signed. Once you verify the signature as coming from me, any anti-virus hits are false positives. When in doubt, download the files directly from here!
